---
- include_tasks: define_dynamic_handlers.yml

- name: place sync script
  template:
    src: "sync2s3.sh.j2"
    dest: "{{ item.install_path }}/sync2s3_{{ item.name }}.sh"
    mode: 0755
    owner: "{{ item.user }}"
    group: "{{ item.grp | default(item.user) }}"
  notify: "restart-sync2s3_{{item.name}}"
- name: place config file
  template:
    src: "sync2s3.cfg.j2"
    dest: "{{ item.install_path }}/sync2s3_{{ item.name }}.cfg"
    mode: 0600
    owner: "{{ item.user }}"
    group: "{{ item.grp|default(item.user) }}"
  notify: "restart-sync2s3_{{item.name}}"
- name: place logrotate file
  template:
    src: "sync2s3.logrotate.j2"
    dest: "/etc/logrotate.d/sync2s3_{{ item.name }}"
    mode: 0644
    owner: "root"
    group: "root"
- name: Install systemd config
  template:
    src: "sync2s3.systemd.j2"
    dest: "/etc/systemd/system/sync2s3_{{item.name}}.service"
    mode: 0644
    owner: "root"
    group: "root"
  notify: "daemon-reload"
- name: Force handlers to run (i.e. daemon-reload if it needs to happen)
  meta: flush_handlers
- name: Start and enable sync2s3 service for {{item.name}}
  systemd:
    enabled: "yes"
    state: "started"
    name: "sync2s3_{{item.name}}.service"