---
# - name: ensure inotify-tools is installed
#   apt:
#     name: "inotify-tools"
#     state: "present"

- name: install scripts, configs, and @reboot-cronjob...
  include_tasks: install_files.yml
  with_items: "{{ sync2s3 | default([]) }}"