---
- name: ensure inotify-tools is installed
  apt:
    name: "inotify-tools"
    state: "present"

- name: adjust max_user_watches with sysctl
  sysctl:
    name: "fs.inotify.max_user_watches"
    value: "32768"
    sysctl_set: "yes"
    reload: "yes"

- name: install scripts, configs, systemd services...
  include_tasks: install_files.yml
  with_items: "{{ sync2s3 | default([]) }}"